---
- name: Setup server
  hosts: localhost
  tags: setup
  tasks:
    - name: Add user '{{ login_account_username }}' and append to 'sudo' group
      ansible.builtin.user:
        name: "{{ login_account_username }}"
        shell: /bin/bash
        groups: sudo
        append: true

    - name: Group 'sudo' to have nopasswd
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo ALL='
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: Install docker requirements
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Install docker key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Install docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable

    - name: Install docker
      ansible.builtin.apt:
        name: docker-ce

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ login_account_username }}"
        state: present
        key: "{{ login_account_ssh_key }}"

    - name: Disable root ssh login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin\s+yes'
        line: '# PermitRootLogin yes'

    - name: Disable root password
      ansible.builtin.user:
        name: root
        password: '!'

- name: Install Valheim
  hosts: localhost
  tags: valheim
  tasks:
    - name: Add user '{{ valheim_account_username }}' and append to 'docker' group
      ansible.builtin.user:
        name: "{{ valheim_account_username }}"
        password: '!'
        shell: /bin/false
        groups: docker
        append: true

    - name: Create directories
      ansible.builtin.file:
        state: directory
        path: "~{{ valheim_account_username }}/valheim-server/{{ item }}"
        owner: "{{ valheim_account_username }}"
        group: "{{ valheim_account_username }}"
        mode: "0775"
      with_items: [config, data]

    - name: Create docker-compose.yml
      ansible.builtin.template:
        src: valheim.docker-compose.yml
        dest: "~{{ valheim_account_username }}/valheim-server/docker-compose.yaml"
        owner: "{{ valheim_account_username }}"
        group: "{{ valheim_account_username }}"
        mode: "0775"

- name: Start Valheim
  hosts: localhost
  tags: valheim
  collections:
    - community.docker
  become: yes
  become_user: "{{ valheim_account_username }}"
  tasks:
    - name: Start container
      community.docker.docker_compose_v2:
        project_src: "~{{ valheim_account_username }}/valheim-server/"
        state: restarted
